CREATE TABLE APPROVAL_HISTORY (
    HISTORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOC_ID INT NOT NULL,                    -- 문서 ID
    APPROVER_ID VARCHAR(50) NOT NULL,       -- 결재자 ID
    ACTION VARCHAR(20) DEFAULT 'PENDING',   -- 결재 액션 (PENDING, APPROVED, REJECTED)
    COMMENTS TEXT,                          -- 결재 의견
    ACTION_DATE DATETIME,                   -- 결재 처리 일시
    STEP_ORDER INT,                         -- 결재 순서
    FOREIGN KEY (DOC_ID) REFERENCES DOCUMENTS(DOC_ID) ON DELETE CASCADE,
    FOREIGN KEY (APPROVER_ID) REFERENCES USERS(ID)
);