CREATE TABLE DOCUMENTS (
    DOC_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOC_TYPE VARCHAR(50) NOT NULL,          -- 기안서 종류
    TITLE VARCHAR(255) NOT NULL,            -- 제목
    STATUS VARCHAR(20) DEFAULT 'PENDING',   -- 결재 상태 (PENDING, APPROVED, REJECTED)
    INITIATOR_ID VARCHAR(50) NOT NULL,      -- 기안자 ID (USERS 테이블의 ID 참조)
    DRAFT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, -- 기안일
    JSON_CONTENT JSON,                      -- 상세 내용 (MySQL의 JSON 타입 활용)
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (INITIATOR_ID) REFERENCES USERS(ID)
);